version: '3.8'

services:
  nginx:
    container_name: nginx
    image: nginx:1.23.0-alpine
    ports:
      - 80:80
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  backend:
    container_name: outside-backend
    restart: always
    build:
      context: .
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - redis
    environment:
      PORT: 3000
      JWT_SECRET: ${JWT_SECRET:?err}
      JWT_EXPIRES: ${JWT_EXPIRES:?err}
      POSTGRES_DB: outside
      POSTGRES_USER: bromanla
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?err}
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
      NODE_ENV: production
  postgres:
    container_name: outside-postgres
    restart: always
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=bromanla
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?err}
      - POSTGRES_DB=outside
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - postgres-data:/var/lib/postgresql/data
  redis:
    container_name: outside-redis
    restart: always
    image: "redis:alpine"
    ports:
     - 6379:6379
    volumes:
      - redis-data:/data
volumes:
  postgres-data:
  redis-data:
